/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Registros;
import Vistas.Registro;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        this.setSize(965, 600);
        this.setLocation(465, 235);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jplIndex = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jblUsuario = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jblPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jbtIniciar = new javax.swing.JButton();
        jbtRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jplIndex.setBackground(new java.awt.Color(255, 255, 255));
        jplIndex.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo Proyecto.png"))); // NOI18N
        jplIndex.add(jLabel1);
        jLabel1.setBounds(170, 0, 620, 260);

        jblUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jblUsuario.setText("Usuario:");
        jplIndex.add(jblUsuario);
        jblUsuario.setBounds(290, 310, 90, 40);

        jtfUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jplIndex.add(jtfUsuario);
        jtfUsuario.setBounds(420, 310, 250, 40);

        jblPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jblPassword.setText("Password:");
        jplIndex.add(jblPassword);
        jblPassword.setBounds(290, 370, 100, 40);
        jplIndex.add(jPasswordField1);
        jPasswordField1.setBounds(420, 370, 250, 40);

        jbtIniciar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtIniciar.setText("Iniciar");
        jbtIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIniciarActionPerformed(evt);
            }
        });
        jplIndex.add(jbtIniciar);
        jbtIniciar.setBounds(410, 450, 100, 40);

        jbtRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtRegistrar.setText("Registrar");
        jbtRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRegistrarActionPerformed(evt);
            }
        });
        jplIndex.add(jbtRegistrar);
        jbtRegistrar.setBounds(540, 450, 100, 40);

        jDesktopPane1.setLayer(jplIndex, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplIndex, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplIndex, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIniciarActionPerformed
        // TODO add your handling code here:
        String usua=jtfUsuario.getText();
        String con=jPasswordField1.getText();
        Registros a= new Registros(usua, con);
        a.iniciarS();
        if (a.iniciarS()=="no") {
             JOptionPane.showMessageDialog(null, "Datos erroneos"); 
        }if(a.iniciarS()=="si"){
            Registros c=new Registros(usua,con);
            this.setVisible(false);
            Menu b=new Menu();
            b.setVisible(true);
        }
        
       
        
    }//GEN-LAST:event_jbtIniciarActionPerformed

    private void jbtRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRegistrarActionPerformed
            this.setVisible(false);
            Registro b=new Registro();
            b.setVisible(true);
    }//GEN-LAST:event_jbtRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel jblPassword;
    private javax.swing.JLabel jblUsuario;
    private javax.swing.JButton jbtIniciar;
    private javax.swing.JButton jbtRegistrar;
    private javax.swing.JPanel jplIndex;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables

    private void acceder() {
        
    }
}
