/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import Clases.Registros;
import javax.swing.JOptionPane;
/**
 *
 * @author CB07
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form R
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRegistrar = new javax.swing.JPanel();
        jlbNombre = new javax.swing.JLabel();
        jlbApepat = new javax.swing.JLabel();
        jlbApemat = new javax.swing.JLabel();
        jlbUsuario = new javax.swing.JLabel();
        jlbPassword = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfApepat = new javax.swing.JTextField();
        jtfApemat = new javax.swing.JTextField();
        jtfUsuario = new javax.swing.JTextField();
        jpfPassword = new javax.swing.JPasswordField();
        jlbPasswordrepetible = new javax.swing.JLabel();
        jpfPasswordRepetible = new javax.swing.JPasswordField();
        jbtAgregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jlbLogoproyecto = new javax.swing.JLabel();
        jlbLogoempresa = new javax.swing.JLabel();
        jlbNumeroTelefono = new javax.swing.JLabel();
        jtfNumeroTelefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnRegistrar.setBackground(new java.awt.Color(255, 255, 255));

        jlbNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbNombre.setText("Nombre");

        jlbApepat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbApepat.setText("Apellido Paterno:");

        jlbApemat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbApemat.setText("Apellido Materno:");

        jlbUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbUsuario.setText("Usuario");

        jlbPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbPassword.setText("Nueva Contraseña:");

        jtfNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtfApepat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtfApemat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtfUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jlbPasswordrepetible.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbPasswordrepetible.setText("Repite Contraseña:");

        jbtAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtAgregar.setText("Registrar");
        jbtAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAgregarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlbLogoproyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo Proyecto icono.png"))); // NOI18N

        jlbLogoempresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo Empresa icono.png"))); // NOI18N

        jlbNumeroTelefono.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbNumeroTelefono.setText("Número de Teléfono");

        jtfNumeroTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jpnRegistrarLayout = new javax.swing.GroupLayout(jpnRegistrar);
        jpnRegistrar.setLayout(jpnRegistrarLayout);
        jpnRegistrarLayout.setHorizontalGroup(
            jpnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRegistrarLayout.createSequentialGroup()
                .addComponent(jlbLogoempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnRegistrarLayout.createSequentialGroup()
                        .addGroup(jpnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbPasswordrepetible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbApepat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbApemat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbNumeroTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpfPassword)
                            .addComponent(jtfUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jtfApemat, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jtfApepat, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jtfNumeroTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jpfPasswordRepetible)))
                    .addGroup(jpnRegistrarLayout.createSequentialGroup()
                        .addComponent(jbtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbLogoproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnRegistrarLayout.setVerticalGroup(
            jpnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRegistrarLayout.createSequentialGroup()
                .addGroup(jpnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnRegistrarLayout.createSequentialGroup()
                        .addComponent(jlbLogoempresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnRegistrarLayout.createSequentialGroup()
                        .addGroup(jpnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnRegistrarLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jpnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jlbLogoproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(jpnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbApepat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfApepat, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbApemat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfApemat, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbPasswordrepetible, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpnRegistrarLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jpfPasswordRepetible, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jpnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNumeroTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addGap(19, 19, 19)))
                .addGroup(jpnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAgregarActionPerformed
        String nom=jtfNombre.getText();
        String apepa=jtfApepat.getText();
        String apema=jtfApemat.getText();
        String usu=jtfUsuario.getText();
        String con=jpfPassword.getText();
        String cel=jtfNumeroTelefono.getText();
        String con2=jpfPasswordRepetible.getText();
if(con.equalsIgnoreCase(con2)){
    if(cel.length()>10){
     JOptionPane.showMessageDialog(null, "Formato invalido");
    }else{
    Registros a=new Registros(nom,apepa,apema,usu,con,cel);
    a.registrar();
    JOptionPane.showMessageDialog(null, "Registro exitoso");
    abrirIndex();
    }
}else{
    JOptionPane.showMessageDialog(null, "Contraseña incorrecta repita acción");
}
        
        
    }//GEN-LAST:event_jbtAgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        abrirIndex();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbtAgregar;
    private javax.swing.JLabel jlbApemat;
    private javax.swing.JLabel jlbApepat;
    private javax.swing.JLabel jlbLogoempresa;
    private javax.swing.JLabel jlbLogoproyecto;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JLabel jlbNumeroTelefono;
    private javax.swing.JLabel jlbPassword;
    private javax.swing.JLabel jlbPasswordrepetible;
    private javax.swing.JLabel jlbUsuario;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JPasswordField jpfPasswordRepetible;
    private javax.swing.JPanel jpnRegistrar;
    private javax.swing.JTextField jtfApemat;
    private javax.swing.JTextField jtfApepat;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfNumeroTelefono;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables

    private void abrirIndex() {
            this.setVisible(false);
            Index b=new Index();
            b.setVisible(true);
    }
}
