
package Graficos;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import panamahitek.Arduino.PanamaHitek_Arduino;

public class MAin extends javax.swing.JFrame {
    
    PanamaHitek_Arduino Arduino = new PanamaHitek_Arduino();
    Controls c = new Controls();
    
    public MAin() {
        initComponents();
        setSize(494, 342);
        setLocationRelativeTo(null);
        setResizable(false);
        getPorts();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Recursos/1.png"));


        return retValue;
    }

   
    public void getPorts() {
        jcbPuertos.removeAllItems();
        if (Arduino.getPortsAvailable() > 0) {
            List lst = Arduino.getSerialPorts();
            for(int i=0; i<lst.size(); i++){
                jcbPuertos.addItem(lst.get(i));
            }
            //Arduino.getSerialPorts().forEach(i -> jComboBoxPorts.addItem(i));
            jbConectar.setEnabled(true);
            jbConectar.setBackground(new Color(255, 255, 255));
        } else {
            jbConectar.setEnabled(false);
            jbConectar.setBackground(new Color(204, 204, 204));
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbPuertos = new javax.swing.JComboBox<>();
        jbConectar = new javax.swing.JButton();
        jbDesconectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jcbPuertos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbPuertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPuertosActionPerformed(evt);
            }
        });
        jPanel1.add(jcbPuertos);
        jcbPuertos.setBounds(135, 75, 120, 47);

        jbConectar.setText("Conectar");
        jPanel1.add(jbConectar);
        jbConectar.setBounds(120, 180, 140, 50);

        jbDesconectar.setText("Desconectar");
        jPanel1.add(jbDesconectar);
        jbDesconectar.setBounds(290, 180, 130, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbPuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPuertosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPuertosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbConectar;
    private javax.swing.JButton jbDesconectar;
    private javax.swing.JComboBox<String> jcbPuertos;
    // End of variables declaration//GEN-END:variables
}
